version: '3.8'

services:
  nexus_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/nexus:/var/lib/pg/nexus/data
    networks:
      - nexus-network
volumes:
  cache:
    driver: local
networks:
  nexus-network:
    driver: bridge
